In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

Import dataset


In [ ]:
dataset = pd.read_csv('LoanApprovalPrediction.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

Missing values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, :7])
X[:, :7] = imputer.transform(X[:, :7])

In [ ]:
imputer2=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer2.fit(X[:,7:12])
X[:,7:12]=imputer2.transform(X[:,7:12])

In [ ]:
print(X)

[['Male' 'No' 'Graduate' ... 0.0 144.9688041594454 360.0]
 ['Male' 'Yes' 'Graduate' ... 1508.0 128.0 360.0]
 ['Male' 'Yes' 'Graduate' ... 0.0 66.0 360.0]
 ...
 ['Male' 'Yes' 'Graduate' ... 240.0 253.0 360.0]
 ['Male' 'Yes' 'Graduate' ... 0.0 187.0 360.0]
 ['Female' 'No' 'Graduate' ... 0.0 133.0 360.0]]


Encoding independent variable


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), slice(0,6))], remainder='passthrough')
X=ct.fit_transform(X)

In [ ]:
print(X)

[[0.0 1.0 1.0 ... 0.0 144.9688041594454 360.0]
 [0.0 1.0 0.0 ... 1508.0 128.0 360.0]
 [0.0 1.0 0.0 ... 0.0 66.0 360.0]
 ...
 [0.0 1.0 0.0 ... 240.0 253.0 360.0]
 [0.0 1.0 0.0 ... 0.0 187.0 360.0]
 [1.0 0.0 1.0 ... 0.0 133.0 360.0]]


Encoding dependent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.49148595  0.49148595 -0.73278748 ...  0.56669422  0.23537144
   0.2779112 ]
 [ 2.03464615 -2.03464615  1.36465213 ... -0.55816364 -0.54335526
   0.2779112 ]
 [-0.49148595  0.49148595 -0.73278748 ...  0.50737901  0.3232922
  -4.04928443]
 ...
 [-0.49148595  0.49148595  1.36465213 ... -0.55816364 -0.27959299
  -0.00558583]
 [ 2.03464615 -2.03464615  1.36465213 ...  0.28183915 -0.32983342
  -0.00558583]
 [-0.49148595  0.49148595 -0.73278748 ... -0.55816364  1.61698332
   0.2779112 ]]


Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

Prediction

In [1]:
classifier.pred()

NameError: name 'classifier' is not defined